name: Build and deploy

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
          - acceptance
          - unit
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:${{ matrix.tests }}
  dev-deploy:
    name: Development
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: dev
  test-deploy:
    name: Test
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: test
  production-deploy:
    name: Production
    needs: test-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      stage: production
    if: ${{ github.ref == 'refs/heads/main' }}
