name: Build and deploy

on:
  - push

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  dev-deploy:
    name: Development
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: dev
  test-deploy:
    name: Test
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: test
  production-deploy:
    name: Production
    needs: test-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      stage: production
    if: ${{ github.ref == 'refs/heads/main' }}
