name: Build and deploy

on:
  push:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch:
    inputs:
      deploy_to_test:
        description: "Deploy to test environment"
        type: boolean
        default: true
        required: false
      deploy_to_prod:
        description: "Deploy to production environment"
        type: boolean
        default: false
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
          - acceptance
          - unit
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: yarn test:${{ matrix.tests }}
  dev-deploy:
    name: Development
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: dev
  test-deploy:
    name: Test
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage: test
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_test == 'true')
  production-deploy:
    name: Production
    needs: test-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      stage: production
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_prod == 'true')
