name: Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy
        run: yarn deploy
