name: Test and deploy

on:
  - push

jobs:
  test:
    uses: ./.github/workflows/test.yml
  test-deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      stage: test
  production-deploy:
    needs: test-deploy
    uses: ./.github/workflows/deploy.yml
    with:
      stage: production
