name: Test

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          check-latest: true
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
